export const songs = [
    {
        title: "Choosin' Texas",
        artist: "Ella Langley",
        duration_seconds: 187,
        genre: "Country",
        audio_url: "https://example.com/audio/choosin-texas.mp3",
    },
    {
        title: "Man I Need",
        artist: "Olivia Dean",
        duration_seconds: 201,
        genre: "Pop",
        audio_url: "https://example.com/audio/man-i-need.mp3",
    },
    {
        title: "I Just Might",
        artist: "Bruno Mars",
        duration_seconds: 214,
        genre: "Pop",
        audio_url: "https://example.com/audio/i-just-might.mp3",
    },
    {
        title: "Ordinary",
        artist: "Alex Warren",
        duration_seconds: 191,
        genre: "Pop",
        audio_url: "https://example.com/audio/ordinary.mp3",
    },
    {
        title: "Golden",
        artist: "HUNTR/X: EJAE, Audrey Nuna & REI AMI",
        duration_seconds: 198,
        genre: "Pop",
        audio_url: "https://example.com/audio/golden.mp3",
    },
    {
        title: "Stateside",
        artist: "PinkPantheress With Zara Larsson",
        duration_seconds: 176,
        genre: "Dance Pop",
        audio_url: "https://example.com/audio/stateside.mp3",
    },
    {
        title: "Opalite",
        artist: "Taylor Swift",
        duration_seconds: 233,
        genre: "Pop",
        audio_url: "https://example.com/audio/opalite.mp3",
    },
    {
        title: "The Fate Of Ophelia",
        artist: "Taylor Swift",
        duration_seconds: 245,
        genre: "Pop",
        audio_url: "https://example.com/audio/the-fate-of-ophelia.mp3",
    },
    {
        title: "So Easy (To Fall In Love)",
        artist: "Olivia Dean",
        duration_seconds: 205,
        genre: "Soul Pop",
        audio_url: "https://example.com/audio/so-easy-to-fall-in-love.mp3",
    },
    {
        title: "American Girls",
        artist: "Harry Styles",
        duration_seconds: 219,
        genre: "Pop Rock",
        audio_url: "https://example.com/audio/american-girls.mp3",
    },
    {
        title: "Folded",
        artist: "Kehlani",
        duration_seconds: 221,
        genre: "R&B",
        audio_url: "https://example.com/audio/folded.mp3",
    },
    {
        title: "Back To Friends",
        artist: "sombr",
        duration_seconds: 184,
        genre: "Indie Pop",
        audio_url: "https://example.com/audio/back-to-friends.mp3",
    },
    {
        title: "Risk It All",
        artist: "Bruno Mars",
        duration_seconds: 208,
        genre: "Pop",
        audio_url: "https://example.com/audio/risk-it-all.mp3",
    },
    {
        title: "DTMF",
        artist: "Bad Bunny",
        duration_seconds: 230,
        genre: "Latin",
        audio_url: "https://example.com/audio/dtmf.mp3",
    },
    {
        title: "Sleepless In A Hotel Room",
        artist: "Luke Combs",
        duration_seconds: 216,
        genre: "Country",
        audio_url: "https://example.com/audio/sleepless-in-a-hotel-room.mp3",
    },
    {
        title: "Be Her",
        artist: "Ella Langley",
        duration_seconds: 199,
        genre: "Country",
        audio_url: "https://example.com/audio/be-her.mp3",
    },
    {
        title: "Where Is My Husband!",
        artist: "RAYE",
        duration_seconds: 222,
        genre: "Alt Pop",
        audio_url: "https://example.com/audio/where-is-my-husband.mp3",
    },
    {
        title: "Iloveitiloveitiloveit",
        artist: "Bella Kay",
        duration_seconds: 179,
        genre: "Pop",
        audio_url: "https://example.com/audio/iloveitiloveitiloveit.mp3",
    },
    {
        title: "Babydoll",
        artist: "Dominic Fike",
        duration_seconds: 193,
        genre: "Alternative",
        audio_url: "https://example.com/audio/babydoll.mp3",
    },
    {
        title: "Porch Light",
        artist: "Noah Kahan",
        duration_seconds: 227,
        genre: "Folk Pop",
        audio_url: "https://example.com/audio/porch-light.mp3",
    },
    {
        title: "SWIM",
        artist: "BTS",
        duration_seconds: 203,
        genre: "K-Pop",
        audio_url: "https://example.com/audio/swim.mp3",
    },
    {
        title: "Rein Me In",
        artist: "Sam Fender & Olivia Dean",
        duration_seconds: 224,
        genre: "Indie Rock",
        audio_url: "https://example.com/audio/rein-me-in.mp3",
    },
    {
        title: "Titi Me Pregunto",
        artist: "Bad Bunny",
        duration_seconds: 244,
        genre: "Latin",
        audio_url: "https://example.com/audio/titi-me-pregunto.mp3",
    },
    {
        title: "Baile Inolvidable",
        artist: "Bad Bunny",
        duration_seconds: 236,
        genre: "Latin",
        audio_url: "https://example.com/audio/baile-inolvidable.mp3",
    },
    {
        title: "Nuevayol",
        artist: "Bad Bunny",
        duration_seconds: 228,
        genre: "Latin",
        audio_url: "https://example.com/audio/nuevayol.mp3",
    },
    {
        title: "EOO",
        artist: "Bad Bunny",
        duration_seconds: 211,
        genre: "Latin",
        audio_url: "https://example.com/audio/eoo.mp3",
    },
    {
        title: "E85",
        artist: "Don Toliver",
        duration_seconds: 197,
        genre: "Hip-Hop",
        audio_url: "https://example.com/audio/e85.mp3",
    },
    {
        title: "Cigarettes",
        artist: "Morgan Wallen",
        duration_seconds: 215,
        genre: "Country",
        audio_url: "https://example.com/audio/cigarettes.mp3",
    },
    {
        title: "End Of Beginning",
        artist: "Djo",
        duration_seconds: 159,
        genre: "Indie Rock",
        audio_url: "https://example.com/audio/end-of-beginning.mp3",
    },
    {
        title: "Yukon",
        artist: "Justin Bieber",
        duration_seconds: 207,
        genre: "Pop",
        audio_url: "https://example.com/audio/yukon.mp3",
    },
];